springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Users
        url: /v3/api-docs/users
      - name: Analyses  
        url: /v3/api-docs/analyses
      - name: Locations
        url: /v3/api-docs/locations
  api-docs:
    enabled: false
